title: Evan Lori Mahone
title_short: ELM
subtitle: "Trans fem // Artist // Activist // Programmer"
email: evan@bmoretransalliance.com
description: >- # this means to ignore newlines until "baseurl:"
  Evan Lori Mahone's website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "elm2091"
github_username:  "apathinwalking"
cloud_name: "dweooc0sz"

# Build settings
markdown: kramdown
plugins:

sass:
  style: expanded
  sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package.json
  - yarn.lock
  - tasks
  - Rakefile
  - .env
