title: Evan Lori Mahone
title_short: ELM
subtitle: "Trans fem // Artist // Activist // Programmer"
email: evan@bmoretransalliance.com
description: >-
  Evan Lori Mahone's website.
url: "http://evanlori.com"
cloud_name: "evanlori"

collections:
  artwork:
    output: true
  artwork-categories:
    output: true
    layout: artwork-category
    permalink: /artwork/:name/

defaults:
  -
    scope:
      path: ""
      type: artwork
    values:
      layout: "art"
      featured: false
  -
    scope:
      path: ""
      type: artwork-categories
    values:
      layout: "artwork-category"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package.json
  - yarn.lock
  - tasks
  - Rakefile
  - .env
  - .tmp

# Build settings
markdown: kramdown
plugins:

sass:
  style: expanded
  sass_dir: _sass
