title: Evan Lori Mahone
title_short: ELM
subtitle: "Trans fem // Artist // Activist // Programmer"
email: evan@bmoretransalliance.com
description: >-
  Evan Lori Mahone's website.
url: "http://evanlori.com"
cloud_name: "evanlori"

# Build settings
markdown: kramdown
plugins:

sass:
  style: expanded
  sass_dir: _sass

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package.json
  - yarn.lock
  - tasks
  - Rakefile
  - .env
  - .tmp
