title: Evan Lori Mahone
title_short: ELM
subtitle: "Trans fem // Artist // Activist // Programmer"
email: evan@bmoretransalliance.com
description: >-
  Evan Lori Mahone's website.
url: "http://evanlori.com"
cloud_name: "evanlori"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package.json
  - yarn.lock
  - tasks
  - Rakefile
  - .env
  - .tmp

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2

sass:
  style: expanded
  sass_dir: _sass

pagination:
  enabled: true
  per_page: 6
  limit: 0
  permalink: '/page/:num/'
  title: ' - page :num'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
